- name: "FTP Zena installer files to Agents Server Nodes"
  copy: src=../files/zenainstaller/ dest=/tmp/zenainstaller/ owner=root group=root mode=0775
- name: "Make Sure Unzip Installed on Nodes"
  yum: name=unzip state=present
- name: "Installing Zena Controller"
  shell: /tmp/zenainstaller/Controller/install.bin
  ignore_errors: True
- name: "Installing Zena Agent"
  shell: /tmp/zenainstaller/Agent/install.bin
- name: "Querying Zena Agent log"
  shell: 'more /opt/zena/agent/xagent_1.log'
- name: "Querying Zena Agent Status"
  shell: '/opt/zena/bin/LINUX64/zenastat list'
